version: '2'
services:
  nginx_server:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    working_dir: /var/www
    ports: 
      - "80:80"
    volumes:
      - ./www:/var/www
    links:
      - backend
    depends_on:
      - backend
  backend:
    build: 
      context: .
      dockerfile: php/Dockerfile
    working_dir: /var/www
    volumes:
      - ./www:/var/www
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3340:3306"
volumes:
  dbdata: